# Generated by Django 4.0.8 on 2026-09-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
    ]
